language: python
python:
    - "3.4"
install: "pip install -r requirements.txt"

services:
  - postgresql

before_script:
  - psql -U postgres -c "CREATE DATABASE testing_db;" 
  - psql -U postgres -c "CREATE USER foo WITH PASSWORD 'bar';" 
  - psql -U postgres -c "ALTER USER foo CREATEDB;"

script:
    - SECRET_KEY="whatever" ./manage.py test