language: python
python:
    - "3.4"
install: "pip install -r requirements.txt"

services:
  - postgresql

before_script:
  - psql -c "CREATE USER test WITH PASSWORD 'test';"
  - psql -c "ALTER USER test CREATEDB;"

script:
    - SECRET_KEY="whatever" ./manage.py test